---
abstract: 'array index offseting'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  perl: 5.008001
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.008001
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Array-Base
provides:
  Array::Base:
    file: lib/Array/Base.pm
    version: 0.003
requires:
  Lexical::SealRequireHints: 0.003
  XSLoader: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
